rocketmq:
    name-server: 47.103.44.163:9876
    producer:
        group: boot-producer-group
#        enable-msg-trace: true # ??????????
#        access-key: rocketmq2
#        secret-key: 12345678